### ISSUE TITLE
又没有比较新的加密算法 可以实现gui&PPPOE

### ISSUE THREAD

**Issue by fennudeage** [shenxs/singleNet#1]
脑袋疼看的 最好是c++ or c 有Qt基础 还有心跳包是UDP么？ 抓包工具是否可以抓到具体内容 内容是固定的么？

**Comment by shenxs** [comment]
这是用racket(一种scheme的方言)写的,包括界面.
你可以去看openwrt或者python还有一个用windows的powershell脚本写的实现,对于没有racket基础的人可能比较容易看懂
这个拨号器不需要实现pppoE,那是路由器的工作,可能在系统本身也会有相应的系统api可以调用吧

**Comment by shenxs** [comment]
没有实现心跳,但是知道可以抓到包的
