### ISSUE TITLE
麻烦大佬帮我看下这个人写的算法对不对？

### ISSUE THREAD

**Issue by fennudeage** [shenxs/singleNet#2]
https://github.com/purpleroc/rdial  //这是我一模一样根据加密算法抄过去的 发现不行 又因为 https://github.com/WrBug/sxDesk//这个作者写的JAVA客户端是我曾经可以用的 我加群向他请教 他说他的拨号源码用的是第一个人写的（rdial）(他改过的版本)源码他说他弄丢了     后来我做的差不多了 心跳udpsock都写好了 感觉加密算法根本不对 人家又是大佬 每次问两句就不想搭理我了 他一直在回避问题 感觉就是 很迷茫 我用rdial 也不能拨号（改了radius）  现在我不知道 是算法错了 还是我错了 我看不懂md5加密 我只知道账号加密结构 现在只差这个问题了

**Comment by shenxs** [comment]
- 我不是大佬(不太喜欢这个称呼)
- 我写的时候找了一个可以用的项目,对比一下两个程序的输出就好了,就知道你写的对不对了
- 在路由器验证的时候用到了MD5加密吗?是的话java应该有相应的函数库的,直接调用就好了,大多数语言都是有这种常见的加密实现的

**Comment by fennudeage** [comment]
我不知道哪个可以用 唯一可用的 我去加了作者的QQ群 问了他 他不给我rdial源码 他只是提交JAVA客户端其实就是UI 一点营养也没有  你是参考哪里的？作者不愿意像我透露过多信息他源码也不给我
有时装看不见

**Comment by shenxs** [comment]
https://github.com/miao1007/Openwrt-NetKeeper
https://github.com/sunflyer/SimpleNetkeeper
https://github.com/efateva/pssx
https://github.com/ybf1220/OpenWrt-Netkeeper
https://github.com/hufeiya/ShanXun


应该都是可以用的,主要参考了miao1007的原理图,hufeiya的python加密那部分是对的,还看了powershell的版本(比较简洁)

**Comment by fennudeage** [comment]
谢 早睡
